const sections=[['company','Company'],['about','About'],['divisions','Divisions'],['services','Services'],['vision','Vision & Mission'],['whyUs','Why Us'],['clients','Clients'],['compliance','Compliance']];let data=null,current='company';
const $=id=>document.getElementById(id);function esc(v=''){return String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');return j}
async function boot(){try{data=(await api('/api/admin/content')).content;showApp();renderTabs();renderEditor()}catch(e){if(e.message==='Unauthorized')return $('loginView').hidden=false;msg(e.message,true)}}
function showApp(){$('loginView').hidden=true;$('appView').hidden=false}
function renderTabs(){$('tabs').innerHTML=sections.map(([id,n])=>`<button class="tab ${id===current?'active':''}" data-id="${id}">${n}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{current=b.dataset.id;renderTabs();renderEditor()})}
function field(label,key,val,area=false){return `<div class="field"><label>${label}</label>${area?`<textarea data-key="${key}">${esc(val)}</textarea>`:`<input data-key="${key}" value="${esc(val)}">`}</div>`}
function listEditor(key,title,items){return `<div class="field"><label>${title}</label>${items.map((x,i)=>{if(typeof x==='string')return `<div class="item"><div class="itemTop"><b>Item ${i+1}</b><button class="remove" data-remove="${key}" data-i="${i}">Delete</button></div><input data-list="${key}" data-i="${i}" value="${esc(x)}"></div>`;return `<div class="item"><div class="itemTop"><b>Division ${i+1}</b><button class="remove" data-remove="${key}" data-i="${i}">Delete</button></div>${field('Name',`${key}.name.${i}`,x.name)}${field('Description',`${key}.description.${i}`,x.description,true)}</div>`}).join('')}<button class="add" data-add="${key}">+ Add item</button></div>`}
function renderEditor(){const e=$('editor');$('sectionTitle').textContent=sections.find(x=>x[0]===current)[1];if(current==='company'){const c=data.company;e.innerHTML=field('Company name','company.name',c.name)+field('Legal / profile name','company.legalName',c.legalName)+field('Tagline','company.tagline',c.tagline)+`<div class="row">${field('Established','company.established',c.established)}${field('Workforce','company.workforce',c.workforce)}</div>`+`<div class="row">${field('Email','company.email',c.email)}${field('Phone 1','company.phones.0',c.phones[0])}</div>`+field('Phone 2','company.phones.1',c.phones[1])+field('Address','company.address',c.address,true)}else if(current==='about')e.innerHTML=field('About company','about',data.about,true);else if(current==='divisions')e.innerHTML=listEditor('divisions','Divisions',data.divisions);else if(current==='services')e.innerHTML=listEditor('services','Services',data.services);else if(current==='vision')e.innerHTML=field('Vision','vision',data.vision,true)+field('Mission','mission',data.mission,true);else if(current==='whyUs')e.innerHTML=listEditor('whyUs','Why choose ATM GROUPS',data.whyUs);else if(current==='clients')e.innerHTML=listEditor('clients','Valuable clients',data.clients);else if(current==='compliance')e.innerHTML=listEditor('compliance','Compliance / registrations',data.compliance);bindEditor()}
function bindEditor(){document.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>setValue(el.dataset.key,el.value));document.querySelectorAll('[data-list]').forEach(el=>el.oninput=()=>data[el.dataset.list][+el.dataset.i]=el.value);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data[b.dataset.remove].splice(+b.dataset.i,1);renderEditor()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{data[b.dataset.add].push(b.dataset.add==='divisions'?{name:'New division',description:'Add description'}:'New item');renderEditor()})}
function setValue(path,val){const p=path.split('.');let o=data;for(let i=0;i<p.length-1;i++)o=o[p[i]];o[p[p.length-1]]=val}
function msg(t,bad=false){$('status').textContent=t;$('status').className=bad?'bad':'status'}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});await boot()}catch(x){$('loginMsg').textContent=x.message}};
$('save').onclick=async()=>{try{ $('save').disabled=true;await api('/api/admin/content',{method:'PUT',body:JSON.stringify({content:data})});msg('Saved successfully to the website.')}catch(e){msg(e.message,true)}finally{$('save').disabled=false}};$('logout').onclick=async()=>{await api('/api/admin/login',{method:'DELETE'});location.reload()};boot();
